<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BuJo.Integrations.Telegram</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
      <PackageReference Include="Telegram.Bot" Version="22.10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Extensions\Extensions.csproj" />
    </ItemGroup>

</Project>
