<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>BuJo.Host</RootNamespace>
        <UserSecretsId>8d0dbe3f-f92a-435e-8cb5-e19558f177b8</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
        <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Data\Data.csproj" />
      <ProjectReference Include="..\Integrations\Telegram\Telegram.csproj" />
      <ProjectReference Include="..\TelegramBot\TelegramBot.csproj" />
      <ProjectReference Include="..\Web\Web.csproj" />
    </ItemGroup>

</Project>
