<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-HostJobs-8242FC55-4737-4F72-9D54-5861166A2303</UserSecretsId>
        <RootNamespace>BuJo.HostJobs</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3"/>
    </ItemGroup>
</Project>
